// Explicit regeneration only: these fixtures are committed and never regenerated by tests.
// Run from repository root: npx tsx tools/sync-stage0/create-database-fixtures.ts
import { DatabaseSync } from 'node:sqlite';
import { writeFileSync } from 'node:fs';
import { migrations } from '../../apps/mobile/src/db/migrations';
import { LionPocketDatabase } from '../../apps/desktop/src/main/database';

const stamp = '2026-08-10T12:00:00.000Z';
function insert(db: DatabaseSync, table: string, row: Record<string, string | number | null>) {
  const columns = db.prepare(`PRAGMA table_info(${table})`).all().map((r) => String(r.name));
  const keys = Object.keys(row).filter((key) => columns.includes(key));
  db.prepare(`INSERT INTO ${table} (${keys.join(',')}) VALUES (${keys.map(() => '?').join(',')})`)
    .run(...keys.map((key) => row[key]));
}
function populate(db: DatabaseSync, platform: 'mobile' | 'desktop', version: number) {
  const desktop = platform === 'desktop';
  const hasCatalogs = desktop || version >= 2, hasPlanning = desktop || version >= 3;
  const audit = { created_at: stamp, updated_at: stamp };
  if (hasCatalogs) {
    // Remove generated seeds; retain a deliberately small, user-owned catalog.
    db.exec('DELETE FROM categories; DELETE FROM payment_methods; DELETE FROM cards');
    insert(db, 'categories', { id: 'legacy-category', name: 'Categoria própria', kind: 'expense', color: '#123456', ...audit });
    insert(db, 'payment_methods', { id: 'legacy-payment', name: 'Pagamento próprio', ...audit });
    insert(db, 'cards', { id: 'legacy-card', name: 'Cartão próprio', due_day: 21, closing_day: null, ...audit });
  }
  if (hasPlanning) {
    insert(db, 'recurring_expenses', { id: 'legacy-recurring', kind: 'expense', active: 1, description: 'Série antiga', start_month: '2026-08', start_date: '2026-08-10', frequency: 'monthly', interval_count: 1, interval_unit: 'months', anchor_to_actual: 0, manual_months: '', category_id: 'legacy-category', payment_method_id: 'legacy-payment', card_id: null, [desktop ? 'planned_cents' : 'planned_amount_cents']: 1234, due_day: 10, charge_day: null, notes: 'Preservar programação', ...audit, deleted_at: null });
    insert(db, 'installment_purchases', { id: 'legacy-purchase', description: 'Parcelas antigas', category_id: 'legacy-category', payment_method_id: 'legacy-payment', card_id: 'legacy-card', [desktop ? 'installment_cents' : 'installment_amount_cents']: 2000, total_installments: 3, starting_installment: 2, purchase_date: null, first_due_date: '2026-08-21', status: 'active', notes: 'Preservar slots', ...audit, deleted_at: null });
    insert(db, 'goals', { id: 'legacy-goal', name: 'Objetivo antigo', item_model: 'Modelo', link: 'https://example.test/item', category_id: 'legacy-category', [desktop ? 'target_cents' : 'target_amount_cents']: 10000, [desktop ? 'saved_cents' : 'saved_amount_cents']: 0, priority: 'high', due_date: null, status: 'saving', notes: 'Saldo absoluto', ...audit, deleted_at: stamp });
  }
  const base = { kind: 'expense', category_id: hasCatalogs ? 'legacy-category' : null,
    payment_method_id: hasCatalogs ? 'legacy-payment' : null, card_id: null,
    [desktop ? 'planned_cents' : 'planned_amount_cents']: 1234,
    purchase_date: null, due_date: '2026-08-10', notes: 'á, 🦁\nsegunda linha', ...audit };
  insert(db, 'transactions', { ...base, id: 'legacy-manual', description: 'Realizado zero', [desktop ? 'actual_cents' : 'actual_amount_cents']: 0, settled_date: '2026-08-11', status: 'paid', source_type: 'manual', deleted_at: null });
  insert(db, 'transactions', { ...base, id: 'legacy-deleted', description: 'Excluído antigo', [desktop ? 'actual_cents' : 'actual_amount_cents']: null, settled_date: null, status: 'planned', source_type: 'imported', source_id: 'arquivo-antigo:linha:7', deleted_at: hasCatalogs ? stamp : null });
  if (hasPlanning) {
    insert(db, 'transactions', { ...base, id: 'legacy-occurrence', description: 'Ocorrência editada', [desktop ? 'actual_cents' : 'actual_amount_cents']: null, settled_date: null, status: 'planned', due_date: '2026-08-12', source_type: 'recurring', source_id: 'legacy-recurring', occurrence_date: '2026-08-10', deleted_at: null });
    insert(db, 'transactions', { ...base, id: 'legacy-installment', description: 'Parcela', card_id: 'legacy-card', [desktop ? 'actual_cents' : 'actual_amount_cents']: 2000, [desktop ? 'planned_cents' : 'planned_amount_cents']: 2000, settled_date: '2026-08-21', status: 'paid', due_date: '2026-08-21', source_type: 'installment', source_id: 'legacy-purchase', installment_number: 2, installment_total: 3, deleted_at: null });
  }
  if (desktop || version >= 4) {
    insert(db, 'recurring_transaction_priorities', { recurring_id: 'legacy-recurring', position: 4, pinned_from_month: '2026-08', ...audit });
    insert(db, 'transaction_priority_order', { month: '2026-08', transaction_id: 'legacy-manual', position: 8, ...audit });
  }
  if (!desktop && version >= 4) insert(db, 'local_import_records', { source_key: 'arquivo-antigo:linha:7', created_at: stamp });
}
function dump(db: DatabaseSync, name: string, note: string) {
  const tables = db.prepare("SELECT name, sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").all();
  const indexes = db.prepare("SELECT sql FROM sqlite_master WHERE type='index' AND sql IS NOT NULL ORDER BY name").all();
  const quote = (value: unknown) => value === null ? 'NULL' : typeof value === 'number' ? String(value) : `'${String(value).replaceAll("'", "''")}'`;
  const sql: string[] = [`-- ${note}`, 'PRAGMA foreign_keys = OFF;'];
  sql.push(...tables.map((t) => `${t.sql};`));
  for (const table of tables) {
    const rows = db.prepare(`SELECT * FROM ${table.name} ORDER BY rowid`).all();
    for (const row of rows) sql.push(`INSERT INTO ${table.name} (${Object.keys(row).join(',')}) VALUES (${Object.values(row).map(quote).join(',')});`);
  }
  sql.push(...indexes.map((i) => `${i.sql};`));
  sql.push(`PRAGMA user_version = ${db.prepare('PRAGMA user_version').get()!.user_version};`, 'PRAGMA foreign_keys = ON;');
  writeFileSync(`docs/fixtures/local-first/${name}.sql`, sql.join('\n') + '\n');
}
for (const version of [1, 2, 3, 4]) {
  const db = new DatabaseSync(':memory:');
  for (const migration of migrations.slice(0, version)) for (const sql of migration) db.exec(sql);
  db.exec(`PRAGMA user_version=${version}`);
  populate(db, 'mobile', version);
  dump(db, `mobile-v${version}`, `Historical mobile schema v${version} from 276b304; synthetic records only.`);
  db.close();
}
const desktop = new LionPocketDatabase(':memory:');
populate(desktop.db, 'desktop', 10);
desktop.db.exec(`DELETE FROM migrations WHERE version=11; UPDATE migrations SET applied_at='${stamp}'; ALTER TABLE recurring_transaction_priorities DROP COLUMN pinned_from_month`);
dump(desktop.db, 'desktop-v10', 'Reconstructed desktop pre-11 schema from the additive migration in 276b304; synthetic records only.');
desktop.db.close();
