/** Desktop defaults; existing categories keep their IDs, names and custom colors. */
export const standardCategories = [
  ['Moradia', 'expense', '#F2557F'],
  ['Contas da casa', 'expense', '#FF9142'],
  ['Alimentação', 'expense', '#FFC247'],
  ['Transporte', 'expense', '#4CC9F0'],
  ['Moto', 'expense', '#8B5CF6'],
  ['Saúde', 'expense', '#FF6B9A'],
  ['Assinaturas', 'expense', '#C77DFF'],
  ['Lazer', 'expense', '#FF7D54'],
  ['Compras', 'expense', '#E8467C'],
  ['Educação', 'expense', '#2DD4BF'],
  ['Pets/Animais', 'expense', '#F59E6B'],
  ['Casa', 'expense', '#7C9CF5'],
  ['Ferramentas/Projetos', 'expense', '#6366F1'],
  ['Impostos/Taxas', 'expense', '#EF4444'],
  ['Presentes/Apoio', 'expense', '#D946EF'],
  ['Outros', 'expense', '#9C8AA5'],
  ['Salário CLT', 'income', '#34D399'],
  ['Freelance/Programa', 'income', '#22D3EE'],
  ['PIX/Apoio familiar', 'income', '#4ADE80'],
  ['Reembolso', 'income', '#60A5FA'],
  ['Venda', 'income', '#A78BFA'],
  ['Outros', 'income', '#9C8AA5'],
] as const;
