// Rasterize the existing desktop SVG mascot. No image service or network required.
const fs = require('node:fs');
const path = require('node:path');
const Module = require('node:module');
const ts = require('typescript');
const React = require('react');
const { renderToStaticMarkup } = require('react-dom/server');
const sharp = require('sharp');
const source = path.resolve(__dirname, '../../desktop/src/ui/Lion.tsx');
const compiled = new Module(source, module);
compiled.filename = source;
compiled.paths = module.paths;
compiled._compile(ts.transpileModule(fs.readFileSync(source, 'utf8'), {
  compilerOptions: { jsx: ts.JsxEmit.ReactJSX, module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 },
}).outputText, source);
const moods = ['neutral', 'happy', 'proud', 'worried', 'alarmed', 'sleepy', 'roar', 'love', 'eating'];
const accessories = ['none', 'bow', 'glasses', 'crown', 'party'];
const folder = path.resolve(__dirname, '../src/ui/assets/leo');
fs.mkdirSync(folder, { recursive: true });
(async () => {
  const entries = [], imports = [];
  for (const mood of moods) for (const accessory of accessories) for (const blinking of [false, true]) {
    const key = `${mood}-${accessory}${blinking ? '-blink' : ''}`;
    const svg = renderToStaticMarkup(React.createElement(compiled.exports.LionFace, { mood, accessory, blinking }));
    await sharp(Buffer.from(svg)).resize(360, 360).png().toFile(path.join(folder, `${key}@3x.png`));
    const identifier = `leo${entries.length}`;
    imports.push(`import ${identifier} from './assets/leo/${key}.png';`);
    entries.push(`  '${key}': ${identifier},`);
  }
  fs.writeFileSync(path.resolve(__dirname, '../src/ui/leoAssets.ts'), `// Generated by scripts/generate-leo.cjs from desktop Lion.tsx.\nimport type { ImageSourcePropType } from 'react-native';\n${imports.join('\n')}\nexport const leoAssets: Record<string, ImageSourcePropType> = {\n${entries.join('\n')}\n};\n`);
})().catch(error => { console.error(error); process.exitCode = 1; });
