// Generated by scripts/generate-leo.cjs from desktop Lion.tsx.
import type { ImageSourcePropType } from 'react-native';
import leo0 from './assets/leo/neutral-none.png';
import leo1 from './assets/leo/neutral-none-blink.png';
import leo2 from './assets/leo/neutral-bow.png';
import leo3 from './assets/leo/neutral-bow-blink.png';
import leo4 from './assets/leo/neutral-glasses.png';
import leo5 from './assets/leo/neutral-glasses-blink.png';
import leo6 from './assets/leo/neutral-crown.png';
import leo7 from './assets/leo/neutral-crown-blink.png';
import leo8 from './assets/leo/neutral-party.png';
import leo9 from './assets/leo/neutral-party-blink.png';
import leo10 from './assets/leo/happy-none.png';
import leo11 from './assets/leo/happy-none-blink.png';
import leo12 from './assets/leo/happy-bow.png';
import leo13 from './assets/leo/happy-bow-blink.png';
import leo14 from './assets/leo/happy-glasses.png';
import leo15 from './assets/leo/happy-glasses-blink.png';
import leo16 from './assets/leo/happy-crown.png';
import leo17 from './assets/leo/happy-crown-blink.png';
import leo18 from './assets/leo/happy-party.png';
import leo19 from './assets/leo/happy-party-blink.png';
import leo20 from './assets/leo/proud-none.png';
import leo21 from './assets/leo/proud-none-blink.png';
import leo22 from './assets/leo/proud-bow.png';
import leo23 from './assets/leo/proud-bow-blink.png';
import leo24 from './assets/leo/proud-glasses.png';
import leo25 from './assets/leo/proud-glasses-blink.png';
import leo26 from './assets/leo/proud-crown.png';
import leo27 from './assets/leo/proud-crown-blink.png';
import leo28 from './assets/leo/proud-party.png';
import leo29 from './assets/leo/proud-party-blink.png';
import leo30 from './assets/leo/worried-none.png';
import leo31 from './assets/leo/worried-none-blink.png';
import leo32 from './assets/leo/worried-bow.png';
import leo33 from './assets/leo/worried-bow-blink.png';
import leo34 from './assets/leo/worried-glasses.png';
import leo35 from './assets/leo/worried-glasses-blink.png';
import leo36 from './assets/leo/worried-crown.png';
import leo37 from './assets/leo/worried-crown-blink.png';
import leo38 from './assets/leo/worried-party.png';
import leo39 from './assets/leo/worried-party-blink.png';
import leo40 from './assets/leo/alarmed-none.png';
import leo41 from './assets/leo/alarmed-none-blink.png';
import leo42 from './assets/leo/alarmed-bow.png';
import leo43 from './assets/leo/alarmed-bow-blink.png';
import leo44 from './assets/leo/alarmed-glasses.png';
import leo45 from './assets/leo/alarmed-glasses-blink.png';
import leo46 from './assets/leo/alarmed-crown.png';
import leo47 from './assets/leo/alarmed-crown-blink.png';
import leo48 from './assets/leo/alarmed-party.png';
import leo49 from './assets/leo/alarmed-party-blink.png';
import leo50 from './assets/leo/sleepy-none.png';
import leo51 from './assets/leo/sleepy-none-blink.png';
import leo52 from './assets/leo/sleepy-bow.png';
import leo53 from './assets/leo/sleepy-bow-blink.png';
import leo54 from './assets/leo/sleepy-glasses.png';
import leo55 from './assets/leo/sleepy-glasses-blink.png';
import leo56 from './assets/leo/sleepy-crown.png';
import leo57 from './assets/leo/sleepy-crown-blink.png';
import leo58 from './assets/leo/sleepy-party.png';
import leo59 from './assets/leo/sleepy-party-blink.png';
import leo60 from './assets/leo/roar-none.png';
import leo61 from './assets/leo/roar-none-blink.png';
import leo62 from './assets/leo/roar-bow.png';
import leo63 from './assets/leo/roar-bow-blink.png';
import leo64 from './assets/leo/roar-glasses.png';
import leo65 from './assets/leo/roar-glasses-blink.png';
import leo66 from './assets/leo/roar-crown.png';
import leo67 from './assets/leo/roar-crown-blink.png';
import leo68 from './assets/leo/roar-party.png';
import leo69 from './assets/leo/roar-party-blink.png';
import leo70 from './assets/leo/love-none.png';
import leo71 from './assets/leo/love-none-blink.png';
import leo72 from './assets/leo/love-bow.png';
import leo73 from './assets/leo/love-bow-blink.png';
import leo74 from './assets/leo/love-glasses.png';
import leo75 from './assets/leo/love-glasses-blink.png';
import leo76 from './assets/leo/love-crown.png';
import leo77 from './assets/leo/love-crown-blink.png';
import leo78 from './assets/leo/love-party.png';
import leo79 from './assets/leo/love-party-blink.png';
import leo80 from './assets/leo/eating-none.png';
import leo81 from './assets/leo/eating-none-blink.png';
import leo82 from './assets/leo/eating-bow.png';
import leo83 from './assets/leo/eating-bow-blink.png';
import leo84 from './assets/leo/eating-glasses.png';
import leo85 from './assets/leo/eating-glasses-blink.png';
import leo86 from './assets/leo/eating-crown.png';
import leo87 from './assets/leo/eating-crown-blink.png';
import leo88 from './assets/leo/eating-party.png';
import leo89 from './assets/leo/eating-party-blink.png';
export const leoAssets: Record<string, ImageSourcePropType> = {
  'neutral-none': leo0,
  'neutral-none-blink': leo1,
  'neutral-bow': leo2,
  'neutral-bow-blink': leo3,
  'neutral-glasses': leo4,
  'neutral-glasses-blink': leo5,
  'neutral-crown': leo6,
  'neutral-crown-blink': leo7,
  'neutral-party': leo8,
  'neutral-party-blink': leo9,
  'happy-none': leo10,
  'happy-none-blink': leo11,
  'happy-bow': leo12,
  'happy-bow-blink': leo13,
  'happy-glasses': leo14,
  'happy-glasses-blink': leo15,
  'happy-crown': leo16,
  'happy-crown-blink': leo17,
  'happy-party': leo18,
  'happy-party-blink': leo19,
  'proud-none': leo20,
  'proud-none-blink': leo21,
  'proud-bow': leo22,
  'proud-bow-blink': leo23,
  'proud-glasses': leo24,
  'proud-glasses-blink': leo25,
  'proud-crown': leo26,
  'proud-crown-blink': leo27,
  'proud-party': leo28,
  'proud-party-blink': leo29,
  'worried-none': leo30,
  'worried-none-blink': leo31,
  'worried-bow': leo32,
  'worried-bow-blink': leo33,
  'worried-glasses': leo34,
  'worried-glasses-blink': leo35,
  'worried-crown': leo36,
  'worried-crown-blink': leo37,
  'worried-party': leo38,
  'worried-party-blink': leo39,
  'alarmed-none': leo40,
  'alarmed-none-blink': leo41,
  'alarmed-bow': leo42,
  'alarmed-bow-blink': leo43,
  'alarmed-glasses': leo44,
  'alarmed-glasses-blink': leo45,
  'alarmed-crown': leo46,
  'alarmed-crown-blink': leo47,
  'alarmed-party': leo48,
  'alarmed-party-blink': leo49,
  'sleepy-none': leo50,
  'sleepy-none-blink': leo51,
  'sleepy-bow': leo52,
  'sleepy-bow-blink': leo53,
  'sleepy-glasses': leo54,
  'sleepy-glasses-blink': leo55,
  'sleepy-crown': leo56,
  'sleepy-crown-blink': leo57,
  'sleepy-party': leo58,
  'sleepy-party-blink': leo59,
  'roar-none': leo60,
  'roar-none-blink': leo61,
  'roar-bow': leo62,
  'roar-bow-blink': leo63,
  'roar-glasses': leo64,
  'roar-glasses-blink': leo65,
  'roar-crown': leo66,
  'roar-crown-blink': leo67,
  'roar-party': leo68,
  'roar-party-blink': leo69,
  'love-none': leo70,
  'love-none-blink': leo71,
  'love-bow': leo72,
  'love-bow-blink': leo73,
  'love-glasses': leo74,
  'love-glasses-blink': leo75,
  'love-crown': leo76,
  'love-crown-blink': leo77,
  'love-party': leo78,
  'love-party-blink': leo79,
  'eating-none': leo80,
  'eating-none-blink': leo81,
  'eating-bow': leo82,
  'eating-bow-blink': leo83,
  'eating-glasses': leo84,
  'eating-glasses-blink': leo85,
  'eating-crown': leo86,
  'eating-crown-blink': leo87,
  'eating-party': leo88,
  'eating-party-blink': leo89,
};
